-   id: sort-cmake-lists
    name: Sort CMake file/library lists
    entry: sort-cmake-lists
    language: python
    files: CMakeLists\.txt$|\.cmake$
    description: Sort argument lists in CMake commands alphabetically.
